### ISSUE TITLE
stops at an error --  can't open /tmpFiles//RDPotus.tax

### ISSUE THREAD

**Issue by dimbakz** [hildebra/lotus2#11]
Dr Falk Hildebrand, 
Thank you for Lotus2 - as a great addition to lotus.

I have a question -- after installation (I used docker a "penanalytics/r-base" as Ubuntu basis for lotus2 installation) and run example an example via  

        "perl ./lotus2.pl -i Example/ -m Example/miSeqMap.sm.txt -s configs/sdm_miSeq.txt -p miSeq -o /mydir/myTestRun"

the script does not perform analysis and stops at an error -- 

        "Can't open /mydir/myTestRun/tmpFiles//RDPotus.tax :
        No such file or directory at ./lotus2.pl line 4078."

I tried reinstalling several times, and also used the desktop UBUNTU version image. But the error occurred every time.

Could you help with this issue?
Sincerely, Dmitry

run log:

--------------------------------------------------------------------------------
 00:00:00 LotuS 2.00
          COMMAND
          perl ./lotus2.pl -i Example/ -m Example/miSeqMap.sm.txt
          -s configs/sdm_miSeq.txt -p miSeq -o /mydir/myTestRun
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 00:00:00 Reading mapping file
          Sequence files are indicated in mapping file.
          Switching to paired end read mode
--------------------------------------------------------------------------------
de novo sequence clustering with UPARSE into OTU's
------------ I/O configuration --------------
Input=   Example/
Output=  /mydir/myTestRun
TempDir= /mydir/myTestRun/tmpFiles/
------------ Configuration LotuS --------------
Sequencing platform=miseq
AmpliconType=SSU
OTU id=0.97
min unique read abundance=-1
UCHIME_REFDB, ABSKEW=/lotus2//DB//rdp_gold.fa, 2
OTU, Chimera prefix=OTU, CHIMERA_
TaxonomicGroup=bacteria
keeping taxonomic unclassified OTU's in matrix
--------------------------------------------
--------------------------------------------------------------------------------
 00:00:00 Demultiplexing, filtering, dereplicating input files, this
          might take some time..
          check progress at /mydir/myTestRun/LotuSLogS/LotuS_progout.log
 00:00:01 Finished primary read processing with sdm:
          Reads processed: 1,250; 1,250 (pair 1;pair 2)
          Rejected: 932; 932
          Accepted (Mid+High qual): 318; 318 (110; 110 were end-trimmed)
          For an extensive report see /mydir/myTestRun/LotuSLogS//demulti.log
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 00:00:01 UPARSE core routine
          Cluster at 97
 00:00:01 Finished
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 00:00:01 Extending and merging pairs of OTU Seeds
--------------------------------------------------------------------------------
sdms /mydir/myTestRun/tmpFiles//otu_seeds.1.singl.fq
--------------------------------------------------------------------------------
 00:00:01 Found 24 fasta seed sequences based on seed extension and read merging
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 00:00:05 Ref chimera filter using usearch uchime2_ref
          Total removed OTUs: (0/24)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 00:00:05 Found 0 OTU's using minimap2 (phiX0: /lotus2//DB//phiX.fasta)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 00:00:05 Postfilter:
          Extended logs active, contaminant and chimeric matrix will be created.
          After filtering 24 OTU (289 reads) remaining in matrix.
--------------------------------------------------------------------------------
Can't open /mydir/myTestRun/tmpFiles//RDPotus.tax :
No such file or directory at ./lotus2.pl line 4078.

**Comment by hildebra** [comment]
Hey, 
just tried a test run with your option, but runs fine on our systems.
looks to me, like RDP classifier didn't run correctly. This can be tricky to install on some systems, please ensure that you have a working java version on the cluster (or I would recommend to just use  option "-simBasedTaxo lambda". 
In the logdir, there is a file called "LotuS_cmds.log". Last line is the last command that was excecuted, close by should be the call to RDP, please try to just run this command by itself.
best, Falk

**Comment by splaisan** [comment]
Sorry to reopen this, I just installed using the perl script and can run the second example (lambda) but not the first.
I wonder if I am not missing some dependencies

```
./lotus2 -i Example/ -m Example/miSeqMap.sm.txt -o myTestRun

No sdm Option specified, using standard miSeq sdm options (/opt/biotools/lotus2/configs/sdm_miSeq.txt)Unknown tax option: -1
%@#%@#%@#%@%@#@%#@%#@#%@#%@#%@#@%#@%#@%#@#%@#%@#%@##
      LotuS2 encounterend an error:
Unknown tax option: -1

First check if the last error occured in a program called by LotuS2 
"tail myTestRun/LotuSLogS/LotuS_progout.log"
, if there is an obvious solution (e.g. external program breaking, this we can't fix). To see (and excecute) the last commands by the pipeline, run 
"tail myTestRun/LotuSLogS/LotuS_cmds.log".
In case you decide to contact us on "https://github.com/hildebra/lotus2/", please try to include information from these approaches in your message, this will increase our response time. Thank you.
%@#%@#%@#%@%@#@%#@%#@#%@#%@#%@#@%#@%#@%#@#%@#%@#%@##
```
the run log contains:

```
No sdm Option specified, using standard miSeq sdm options (/opt/biotools/lotus2/configs/sdm_miSeq.txt)Unknown tax option: -1(base)
```

the other log is just empty

Thanks for your help

**Comment by hildebra** [comment]
Hey, I couldn't reproduce the error locally, but I inserted some extra checks at the code that stopped LotuS2. Could you pull the latest version and try again? thanks, Falk
