### ISSUE TITLE
SDM CentOS7

### ISSUE THREAD

**Issue by uloeber** [hildebra/lotus2#13]
SDM requires some libraries which are not in the default yum repos. Is there a workaround for the installation on CentOS?
```
lotus2/bin/sdm: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by lotus2/bin/sdm)
lotus2/bin/sdm: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by lotus2/bin/sdm)
lotus2/bin/sdm: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by lotus2/bin/sdm)
lotus2/bin/sdm: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by lotus2/bin/sdm)
lotus2/bin/sdm: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by lotus2/bin/sdm)
```
Thanks in advance :)
Ulrike

**Comment by nsoranzo** [comment]
Maybe you can try with the conda package: https://anaconda.org/bioconda/lotus2 or the Docker image: https://quay.io/repository/biocontainers/lotus2

**Comment by hildebra** [comment]
The problem is that conda does not have yet the latest sdm, I would guess? (which has the massive speed improvements). We're currently trying to get a static compile working with the multithread, but not that easy..

**Comment by hildebra** [comment]
Hey Ulrike, this will take some time (might be unsolavable).. The best would be to get the latest sdm from 
https://github.com/hildebra/sdm
compile it, and replace your sdm (lotus2/bin/sdm) with the one you compiled. In the future, we'll hopefully get the conda version updated to this sdm, once lotus2 is in a more stable version.
best,
Falk

**Comment by uloeber** [comment]
Hey, thanks!
seems like min gcc 8 is needed to compile. I upgraded to v9, but after solving the [first error](https://stackoverflow.com/questions/60336940/g-error-unrecognized-std-c17-what-is-g-version-and-how-to-install), I now receive:
```
g++ -D__STDC_CONSTANT_MACROS -O1 -std=c++17 -g -I./  -c -o Demultipl.o Demultipl.cpp
In file included from gzstream.h:35,
                 from DNAconsts.h:90,
                 from InputStream.h:27,
                 from containers.h:22,
                 from IO.h:23,
                 from Demultipl.cpp:21:
./zlib.h:1420:9: error: ‘z_size_t’ does not name a type; did you mean ‘ssize_t’?
 1420 | ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
      |         ^~~~~~~~
      |         ssize_t
./zlib.h:1454:9: error: ‘z_size_t’ does not name a type; did you mean ‘ssize_t’?
 1454 | ZEXTERN z_size_t ZEXPORT gzfwrite OF((voidpc buf, z_size_t size,
      |         ^~~~~~~~
      |         ssize_t
In file included from ./zlib.h:34,
                 from gzstream.h:35,
                 from DNAconsts.h:90,
                 from InputStream.h:27,
                 from containers.h:22,
                 from IO.h:23,
                 from Demultipl.cpp:21:
./zlib.h:1708:37: error: ‘z_size_t’ has not been declared
 1708 |                                     z_size_t len));
      |                                     ^~~~~~~~
./zlib.h:1743:35: error: ‘z_size_t’ has not been declared
 1743 |                                   z_size_t len));
      |                                   ^~~~~~~~
make: *** [<builtin>: Demultipl.o] Error 1

```
did you ever compiled the new sdm on centos7?

**Comment by hildebra** [comment]
I now (against my expectations) got a working static compile of sdm. Can you please update to the latest lotus (git pull), check that you have sdm v 1.82 and try with this one?
