### ISSUE TITLE
using unoise as clustering

### ISSUE THREAD

**Issue by pedres** [hildebra/lotus2#17]
Hi,

I am processing a set of samples (miseq) and I want to compare OTUs and zOTUs. I have added usearch11 to LotuS and run two commands:
perl lotus2 -i /media/fulgencio/DATOS/species_divergence -m para_LOTUS.txt -o zotus_output-s sdm_miSeqDEF.txt -threads 24 -p miSeq -clustering unoise3 -refDB SLV --taxAligner 1 -derepMin 0 -lulu 0 -buildPhylo 0 -verbosity 3
perl lotus2 -i /media/fulgencio/DATOS/species_divergence -m para_LOTUS.txt -o otus_output -s sdm_miSeqDEF.txt -threads 24 -p miSeq  -refDB SLV --taxAligner 1 -derepMin 0 -lulu 0 -buildPhylo 0 -verbosity 3

When I look to LotuS_run.log I can see in both cases that OTU id=0.97, and when running the unoise3 the message says that "UNOISE core routine Cluster at 97% "Should I pass -id parameter as 1?

Another question is when looking at  demulti.log I see that most of my reverse reads are rejected, and reading that log I cannot understand why this is happening?
Reads processed: 11,632,069; 11,632,069 (pair 1;pair 2)
Rejected: 4,335,473; 10,141,773
Below I paste my smd file
Thank you very much in advance.

Manuel

#sdm options file to control sequence quality filtering, demultiplexing and preparation (can also be used without demultiplexing)
#* indicates alternative quality filtering options, saved in *.add.fna etc. files separately from initial quality filtered dataset
#sequence length refers to sequence length AFTER removal of Primers, Barcodes and trimming. this ensures that downstream analyis tools will have appropiate sequence information
#options with a star in front are lenient parameters for mid qual sequences (only used for estimating OTU abundance, not for OTU building itself).
minSeqLength	250
maxSeqLength	256
minAvgQuality	27
*minSeqLength	170
*minAvgQuality	20
#truncate total Sequence length to X (length after Barcode, Adapter and Primer removals, set to -1 to deactivate)
TruncateSequenceLength	-1

#Ambiguous bases in Sequence
maxAmbiguousNT	0
*maxAmbiguousNT	1

#sequence is discarded if a homonucleotide run in sequence is longer
maxHomonucleotide	8

#Filter whole sequence if one window of quality scores is below average
QualWindowWidth	50
QualWindowThreshhold	25

#Trim the end of a sequence if a window falls below quality threshhold. Useful for removing low qulaity trailing ends of sequence
TrimWindowWidth	20
TrimWindowThreshhold	25

#Probabilistic max number of accumulated sequencing errors. After this length, the rest of the sequence will be deleted. Complimentary to TrimWindowThreshhold. (-1) deactivates this option.
maxAccumulatedError	0.75
*maxAccumulatedError	-1
#Binomial error model of expected errors per sequence (see https://github.com/fpusan/moira), to deactivate, set BinErrorModelAlpha to -1
BinErrorModelMaxExpError	2.5
BinErrorModelAlpha	-1

#Max Barcode Errors 
maxBarcodeErrs	0
maxPrimerErrs	0

#keep Barcode / Primer Sequence in the output fasta file - in a normal 16S analysis this should be deactivated (0) for Barcode and de-activated (0) for primer
keepBarcodeSeq	0
keepPrimerSeq	0

#set fastqVersion to 1 if you use Sanger, Illumina 1.8+ or NCBI SRA files. Set fastqVersion to 2, if you use Illumina 1.3+ - 1.7+ or Solexa fastq files.  "auto" will look for typical characteristics of either of these and choose the quality offset score automatically.
fastqVersion	auto

#if one or more files have a technical adapter still included (e.g. TCAG 454) this can be removed by setting this option
TechnicalAdapter	

#delete X NTs (e.g. if the first 5 bases are known to have strange biases)
TrimStartNTs	0

#correct PE header format (1/2) this is to accomodate the illumina miSeq paired end annotations 2="@XXX 1:0:4" insteand of 1="@XXX/1". Note that the format will be automatically detected
PEheaderPairFmt	1

#sets if sequences without match to reverse primer (ReversePrimer) will be accepted (T=reject ; F=accept all); default=F
RejectSeqWithoutRevPrim	F
#*RejectSeqWithoutRevPrim	F
#sets if sequences without a forward (LinkerPrimerSequence) primer will be accepted (T=reject ; F=accept all); default=F
RejectSeqWithoutFwdPrim	F
#*RejectSeqWithoutFwdPrim	F

#this option should be "T" if your amplicons are possibly shorter than a single read in a paired end sequencing run (e.g. if the 16S amplicon length is 200bp in a 250x2 miSeq run, set this to "T"). This option increases runtime by 10%, if in doubt just set to "T". *Requires* LinkerPrimerSequence and ReversePrimer to be defined in mapping file.
AmpliconShortPE	T

#options for difficulties during sequencing library construction
#checks if pair1 and pair2 were switched (ignore if single read data)
CheckForMixedPairs	F
#checks if whole amplicon was reverse-transcribed sequenced (not switched, just reverse translated)
CheckForReversedSeqs	F

**Comment by pedres** [comment]
Hi,

I have just tested unoise3 with different -id parameters and always give the same number of zotus

**Comment by hildebra** [comment]
Hey Manuel,
the unoise parameter is indeed not used, good suggestion to remove it from the output, will add this to next lotus2 release.
about the second read missing: I would look into the LotusLogs/demulti* log files, they're quire detailed and should give you an indication why the second read gets filtered out. But note that the first read is only used for unoise/uparse, so probably not very important. Second read is mostly used to increase the tax assignment confidence.
hth,
Falk

**Comment by pedres** [comment]
Hi Falk,

Thanks for your help.  I maybe found a bug when LotuS makes the phyloseq object, that does not occurr with the biom file. In my set of samples some of them have a "name" that is a number (i.e. the "3" in 3_S3_L001_R1_001.fastq) and these samples are not incorporated into the phyloseq object, whereas all of them are perfectly incorporated into the biom file. These samples came from an old miSeq run where the provider did not include our sample names, so I consider that it should be not a problem for anybody...
I have written an email to you (from fuleskipe@gmail) asking how to aling sequences with mafft (it is included in LotusS via -f) and how may I choose the mafft aligment algorithm. Anyway, I probably do not build the tree from within LotuS because I will remove Archaea, contaminants, mitochondria,...

Thanks for your help again,

Manuel

**Comment by ozkurt** [comment]
Hello Manuel,

The bug about the sample names starting with a number is fixed now.

Otherwise, if you use the "buildPhylo 1" option, it will use mafft by default (the resulting file is named as OTU.fna).

Thanks!
Ezgi
