### ISSUE TITLE
OTU table is not generated while test run 

### ISSUE THREAD

**Issue by Mushahid2521** [hildebra/lotus2#22]
I have installed lotus2 with bioconda and cloned the github repo. When I try to run the example with the following command 
`lotus2 -i Example/ -m Example/miSeqMap.sm.txt -o myTestRun`  
It doesn't generate any OTU table in the output directory rather I get several warnings and errors.

**Comment by hildebra** [comment]
Hey, can you please paste all the errors that you get on console here? Tbh, sounds like the install wasn't correct, might be some missing software etc.

**Comment by Mushahid2521** [comment]
Thanks I got to run it by manual installation.
