### ISSUE TITLE
Concatenation error generates empty mapping files

### ISSUE THREAD

**Issue by arachloroptera** [hildebra/lotus2#23]
### When I run the following to create a map:
`/home/miniconda3/envs/lotus2/share/lotus2-2.21-0/lotus2 -create_map 01_map`

### An empty mapping file is created accompanied by the following message:
`Use of uninitialized value $first in concatenation (.) or string at /home/miniconda3/envs/lotus2/share/lotus2-2.21-0/lotus2 line 5667.`
` common prefix`
`Map is 01_map`
`Please check that all files required are present in map 01_map.`
`Use of uninitialized value $pathPre in concatenation (.) or string at /home/miniconda3/envs/lotus2/share/lotus2-2.21-0/lotus2 line 5756.`

### The corresponding lines are:

5667: `print "$first common prefix\n";`

5756: `print "==========================\nTo start analysis:\nlotus2 -m $ofile -i $pathPre/ -o [outdir] [further parameters if desired]\n==========================\n";`

I am not familiar enough with Perl to fully understand what is going on, but I am curuious as to why there would be any issue with the script itself when I did not edit in in any way. Am I missing something in terms of my input? I have run this from the input directory containing 100 files (R1 and R2 of 50 samples) in fastq format.

**Comment by ozkurt** [comment]
Hi, thanks for reporting the issue. 
You need to define the input dir to your fastq files:
perl lotus2 -create_map 01_map -i $INPUTdir

Hope this helps.
Ezgi

**Comment by arachloroptera** [comment]
Thank you so much for the quick response. I thought it was taking the current directory as input by default. Thank you for clarifying!
