### ISSUE TITLE
Problem with example trial

### ISSUE THREAD

**Issue by assemahajemlrefaei** [hildebra/lotus2#25]
I have tried to run the example and got errors everytime. I managed to troubleshoot all of those related to DADA2 ASV clustering but now I get an error with building LAMDA index:

'Building LAMBDA index anew (may take up to an hour first time)..
 CMD failed: /home/assem/Downloads/lotus2/lotus2//bin//lambda/lambda_indexer -p blastn -t 1 -d /home/assem/Downloads/lotus2/lotus2//DB//SLV_138.1_SSU.fasta  
see myTestRun2/LotuSLogS/LotuS_progout.log for error log'

Attached is the progout.log and that's its last part:

'Writing OTU matrix to myTestRun2/OTU.txt
Recruited 214 reads in OTU matrix
Done
Time taken: : 3ms
[M::mm_idx_gen::0.002*1.02] collected minimizers
[M::mm_idx_gen::0.003*1.02] sorted minimizers
[M::main::0.003*1.02] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.003*1.02] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.003*1.02] distinct minimizers: 900 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.984
[M::worker_pipeline::0.003*1.02] mapped 15 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: /home/assem/Downloads/lotus2/lotus2//bin//minimap2-2.17_x64-linux/minimap2 -x sr --sr -u both --secondary=no -N 30 -c -t 1 -o myTestRun2/tmpFiles//otu_seeds.fna.phiX.0.cont_hit.paf /home/assem/Downloads/lotus2/lotus2//DB//phiX.fasta myTestRun2/tmpFiles//otu_seeds.fna
[M::main] Real time: 0.004 sec; CPU: 0.004 sec; Peak RSS: 0.003 GB
Loading Subject Sequences and Ids... done.
Dumping Subj Ids... done.
No Seg-File specified, no masking will take place.
Dumping binary seqan mask file... done.

Dumping unreduced Subj Sequences... done.
Generating       0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
 (1) SuffixArray |Killed'

[LotuS_progout.log](https://github.com/hildebra/lotus2/files/9598785/LotuS_progout.log)

**Comment by hildebra** [comment]
Hey, I think this is an out-of-mem error (or out of diskspace) from LAMBDA, please try to rerun on a computer with more memory/allocate more mem. Alternatively, you could also use the vsearch/blast aligner options, or just use RDP classifier.
best, Falk

**Comment by assemahajemlrefaei** [comment]
Hi, 
Thanks for the timely and helpful reply. I will work on that!
