### ISSUE TITLE
How to input demultiplexed, pre-cleaned data

### ISSUE THREAD

**Issue by Xentrics** [hildebra/lotus2#26]
Dear lotus2 team,

I have 16S data that was already demultiplexed & cleaned (i.e., **no primer parts left**).
I created a basic sample map using lotus -create_map and then ran lotus2.

Running lotus2 this way creates a warning: No forward PCR primer for amplicon found in mapping file (column header "ForwardPrimer". This might invalidate chimera checks).

**However**, when I add the primer sequences (i.e., using the -forwardPrimer and -reversePrimer arguments), demultiplexing **fails with an empty output file**.

Is it safe to just run lotus2 without specifying the original primers? **If not**: is there a way to allow reads to pass QC _even if_ the primer is not present anymore?

**Comment by hildebra** [comment]
Dear Xentrics,
in this case it is perfectly fine to run LotuS2 without primers. The reason why you would get empty files if you include the primers is that LotuS2 by default removes all reads without valid amplicon primers (this will remove a lot of noise picked up from the experiment and is an important quality filter). 
Therefore, I would recommend to rerun LotuS2 using the original fastq files, as you might get potentially cleaner results, if the pipeline can check for incorrect reads that don't have an amplicon primer.
hth, Falk

**Comment by Xentrics** [comment]
Thanks for the quick feedback! :)
