### ISSUE TITLE
duplicated ASV sequence

### ISSUE THREAD

**Issue by kingtom2016** [hildebra/lotus2#28]
I am using header name from hashing ASV sequences to integrate ASV table from different datasets. I found that there were duplicated ASV sequences. Why?

Here is my lotus2 command:
lotus2 -i $PWD -m $PWD/1_miSeqMap.sm.txt \
-s /mnt/d/Myfile/DATA/beforework/lotus2/1sdm_miSeq.txt \
-o lotus2_output \
-p miSeq -amplicon_type SSU -tax_group bacteria \
-forwardPrimer $front_f \
-reversePrimer $front_r \
-CL dada2 -refDB SLV -taxAligner lambda \
-rdp_thr 0.7 -buildPhylo 0 -t 6 -sdmThreads 6

The problem still happened when closing LULU option. (-lulu 0)

**Comment by hildebra** [comment]
Hey Kingtom, it's a bit hard to say without looking at the sequences, but one possibility would be that the seed extension process was reconstructing exactly the same sequence. Could you paste the duplicated sequences here, and the file from which you got these? Can you also upload the LotuS_runlog file?
