### ISSUE TITLE
can we multithread the tree making step?

### ISSUE THREAD

**Issue by splaisan** [hildebra/lotus2#32]
Hi All,

It seems that the step: "Building tree (fasttree) and aligning (mafft) OTUs" (run by default) runs on a single thread for quite some time now while I have plenty of free cores available 

ps shows:

```
/opt/miniconda3/envs/lotus2.23/bin/FastTreeMP -nt -gtr -no2nd -spr 4 -log lotus2_pacbio_V1V9/LotuSLogS//fasttree.log -quiet -out lotus2_pacbio_V1V9/OTUphylo.nwk lotus2_pacbio_V1V9/ExtraFiles//OTU.MSA.fna
```

The name FastTreeMP suggests that this could be multithreaded, is it so and if yes can we speed up that step?

Thanks
Stephane

```
lotus2.23
FastTree 2.1.11 Double precision (No SSE3), OpenMP (88 threads)
```

**Comment by hildebra** [comment]
Hey Stephane,
as far as  remember, fasttree will just use all cores available, could you check with "top" how much CPU is getting used up? Yes, fasttree is fast (very fast), but if there is PacBio data my guess would be we're talking about 10k - 100k OTUs, this will just take a very long time.
you could try iqtree (fast mode) option, but I don't think it would be much faster.
Alternatively, consider prunning the tree to OTUs of interest and running fastree on this subset.
best, Falk

**Comment by splaisan** [comment]
Thanks Falk,
As always in such case, the run terminated before you answered
When I looked it was using a single core but maybe that was an intermadiate merging step
I will add here next time I get a run going if I find more evidence

**Comment by splaisan** [comment]
multithread but counting only as 1 in the current stage, from the total time 47min it probably has stages where multiple parallel computation happens as this is not running for that amount of real time

![Screenshot 2023-01-25 at 15 56 01](https://user-images.githubusercontent.com/858516/214596649-42e3cbf0-29f9-4c29-adda-237c410d7ae5.png)

**Comment by splaisan** [comment]
now we speak about multithreding ;-)
you were right Falk!

![Screenshot 2023-01-25 at 16 10 27](https://user-images.githubusercontent.com/858516/214599774-0ac0417f-1cee-4ab4-941c-7def0810eb76.png)

**Comment by hildebra** [comment]
Hey Stepahne, ok great it was solved, and thanks for updating this thread!
best, Falk
