### ISSUE TITLE
Dada2 - installation

### ISSUE THREAD

**Issue by karina121286** [hildebra/lotus2#38]
I wonder how I can Install dada2 to use it when I am using Lotus2, I tried to install this via autoInstall.pl but It did not work. Thanks!

**Comment by hildebra** [comment]
hey, you only need to have DADA2 in your normal R installation. It can be a bit tricky dependent on OS you're using, related to DADA2. Please try to follow the instructions here: https://benjjneb.github.io/dada2/dada-installation.html
