### ISSUE TITLE
Regarding the fate of reads passed through each step of Lotus2

### ISSUE THREAD

**Issue by ShailNair** [hildebra/lotus2#39]
Hi, thank you for this easy-to-use amplicon read analysis pipeline. I was wondering if there is a way to get the number of reads passed through each step. DADA2 provides read counts across samples for each step of processing through:

```
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(mergers, getN), rowSums(seqtab), 
rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoised", "merged", "tabled", "nonchim")
rownames(track) <- sample.names
head(track)
```
It would be very nice if lotus2 could do that.

**Comment by ozkurt** [comment]
Thank you for your question. In the log file LotuS_runlog.txt, you can find information about the number of reads passed/filtered.
Here's an example:
<img width="692" alt="Screenshot 2023-04-20 at 16 30 42" src="https://user-images.githubusercontent.com/8319609/233381915-2716b54f-e224-48d8-a2d3-9630b511311d.png">

**Comment by ShailNair** [comment]
Got it. thanks
