### ISSUE TITLE
issues with sdm and autoInstall

### ISSUE THREAD

**Issue by uloeber** [hildebra/lotus2#4]
Dear Falk, dear Joachim, 
could you check the autoInstall.pl re sdm path?
```
Do you want to
 (1) install utax taxonomic classification databases (16S, ITS)?
 (0) no utax related databases
 Answer:1
Can't open sdm file lotus2//sdm_src/IO.h
```
Linux xxx 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Thanks in advance! I used the linear version provided on the lotus2 webpage.
Best,
Ulrike

**Comment by hildebra** [comment]
This has been resolved now and was related to differences between the github and lotus2.earlham.ac.uk installation packages
