### ISSUE TITLE
contamination of mitochondrion

### ISSUE THREAD

**Issue by codechenx** [hildebra/lotus2#40]
I found that Lotus2(v2.23) or RDP classifier is failed to identify contamination of  mitochondrion, for example, some OTU actually are mitochondrion  sequence, but the taxonomy assignment for these OTU are still bacteria.
The blow is the blast result for a OTU:
<img width="1151" alt="CleanShot_2023-05-02_at_18 09 47_2x_1683043810426" src="https://user-images.githubusercontent.com/38947240/235867305-5e29d5fa-06aa-48e4-bdf4-d86dfd5c1c66.png">

The command line I used:  lotus2 -t 50 -i data -m 16s_map.txt -s sdm_miSeq.txt -o uparse -CL uparse
[sdm_miSeq.txt](https://github.com/hildebra/lotus2/files/11380829/sdm_miSeq.txt)

**Comment by hildebra** [comment]
Hey,
this could be and depends on the RDP database, not something we control in LotuS2 directly. However, you can specifically filter out mitochondrial OTUs, if you give a reference database pointing to mitochondria using this flag:
_-offtargetDB <file>
Remove likely contaminant OTUs/ASVs based on alignment to provided fasta. This option is useful for low-bacterial biomass samples, to remove possible host genome contaminations (e.g. human/mouse genome)_

I don't have a good reference, but just googling I found this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1347373/
If you have a good reference database, I would be very happy to include this in the LotuS2 installation to be added as default option.

best, Falk

**Comment by codechenx** [comment]
Hi Falk,
Thanks for your response. I also don't have a good reference, so I just remove these OTU manually.
