### ISSUE TITLE
Does lotus2 allows mismatches in barcodes

### ISSUE THREAD

**Issue by gooodle** [hildebra/lotus2#41]
I am testing lotus2 on my amplicon sequencing data. I used lima for that but I don't like its demultiplexing report. I read your tutorial but didn't find anywhere stating if mismatches in barcodes can be accommodated.
Would you please help with this question?
Thanks.

**Comment by ozkurt** [comment]
Thank you for your question.
Please see the "maxBarcodeErrs" in the sdm option file (default sdm_miSeq.txt). By default it allows zero errors, but you can change this.

**Comment by gooodle** [comment]
That's great, I will try that. Thanks for your letting me know.

**Comment by gooodle** [comment]
> That's great, I will try that. Thanks for your letting me know.

**Comment by gooodle** [comment]
> Thank you for your question. Please see the "maxBarcodeErrs" in the sdm option file (default sdm_miSeq.txt). By default it allows zero errors, but you can change this.

Hi Ozkurt,

My sequences are PacBio hifi data.  The sequenced are supposed to be dually barcoded. Following your reply, I modified the miSeqMap.sm.txt as follows:

#SampleID	BarcodeSequence	Barcode2ndPair	maxBarcodeErrs
Plate1_A1	CACATATCAGAGTGCG	CACAGAGACACGCACA	6
Plate1_A2	CACATATCAGAGTGCG	TCTCTCTATCGCGCTC	6
.
.
.

As you can see, I added a column of maxBarcodeErrs, but it was somehow ignored by Lotus2, as it showed that:
#Max Barcode Errors 
maxBarcodeErrs	0

Would you please check and let me know if I made a mistake in my miSeqMap.sm.txt?

I greatly appreciate your time and assistance.
