### ISSUE TITLE
parsing single read

### ISSUE THREAD

**Issue by junhuili** [hildebra/lotus2#42]
Hi Falk Hildebrand, 
I wonder if I can parse the single read sequences using lotus2? If so, how can I set the codes? Thanks,
Junhui

**Comment by hildebra** [comment]
Hey Junhui,
yes this is possible, e.g.as used for 454 / PacBio data. 
In the map, specifiy column "fastqFile" as per examples on the webpage, and simply give a single fastq file as input, instead of two read pairs.
best,
Falk

**Comment by junhuili** [comment]
Thanks, Falk.
