### ISSUE TITLE
Error Assigning taxonomy with SILVA

### ISSUE THREAD

**Issue by rjain1990** [hildebra/lotus2#43]
I am getting below error while using SILVA as database. However earlier it worked well with custom database.

*********************
CMD failed: /home/rjain/miniconda3/envs/lotus2/bin/vsearch --usearch_global /zfs/omics/personal/rjain/AMF/output_SLV_lotus2//OTU.fna --db /home/rjain/miniconda3/envs/lotus2/share/lotus2-2.25-0//DB//SLV_138.1_SSU.fasta.vudb  --id 0.75 --query_cov 0.5 -userfields query+target+id+alnlen+mism+opens+qlo+qhi+tlo+thi+ql -userout /zfs/omics/personal/rjain/AMF/output_SLV_lotus2//tmpFiles//tax.0.blast --maxaccepts 100 --maxrejects 100 -strand both --threads 24
*********************

these are the last few line of Lotus_progout.log
***************************
[M::main] CMD: /home/rjain/miniconda3/envs/lotus2/bin/minimap2 -x sr --sr -u both --secondary=no -N 30 -c -t 24 -o /zfs/omics/personal/rjain/AMF/output_SLV_lotus2//tmpFiles//otu_seeds.fna.phiX.0.cont_hit.paf /home/rjain/miniconda3/envs/lotus2/share/lotus2-2.25-0//DB//phiX.fasta /zfs/omics/personal/rjain/AMF/output_SLV_lotus2//tmpFiles//otu_seeds.fna
[M::main] Real time: 0.072 sec; CPU: 0.043 sec; Peak RSS: 0.003 GB
vsearch v2.23.0_linux_x86_64, 251.8GB RAM, 64 cores
https://github.com/torognes/vsearch

Reading UDB file /home/rjain/miniconda3/envs/lotus2/share/lotus2-2.25-0//DB//SLV_138.1_SSU.fasta.vudb

Fatal error: Unable to read from UDB file or invalid UDB file
***************************
Any suggestions are much appreciated. Thanks in advance!

**Comment by hildebra** [comment]
Hey,
can you try switching from vsearch to lambda for doing alignments? It seems the vudb file is corrupted , or was not correctly created. Might be a problem with diskspace?
best,
Falk
