### ISSUE TITLE
errors when using dada2 clustering

### ISSUE THREAD

**Issue by we32i225** [hildebra/lotus2#45]
Hi Lotus team.
Using data that has run perfectly on Lotus2 before (with both RDP and SLV DBs), I changed the clustering option to dada2 as I wanted to have ASVs rather than OTUs. However upon adding -CL dada2, a got a huge range of errors according to the progout log. Am i just missing something in my command (below) or is something wrong?

perl ./lotus2 -i Will -o Will/outputSLV_DADA2 -m WillMAP.txt -refDB SLV -taxAligner blast -CL dada2

many thanks
Will

**Comment by hildebra** [comment]
Hey Will,
nope the command looks perfectly fine. Is something wrong with blast? maybe try : 
lotus2 -i /path/to/Will/ -o Will/outputSLV_DADA2 -m WillMAP.txt -refDB SLV  -CL dada2

hth, Falk

**Comment by we32i225** [comment]
Hi Falk
I tried the code you suggested but i still got the same errors as before, ive attached the progout log. Also when i use SLV DB but don't specify a taxAligner, it defaults to RDP.
[LotuS_progout.log](https://github.com/hildebra/lotus2/files/12439969/LotuS_progout.log)
thanks as always Falk
Will
