### ISSUE TITLE
PR2 version

### ISSUE THREAD

**Issue by slambrechts** [hildebra/lotus2#48]
Hi, 

I was wondering what version of the PR2 database is used in Lotus2? I noticed the taxonomy file of the PR2 DB version that is used with the latest github version of Lotus2 has 7 taxonomic levels, while I read on the PR2 website that:

```
Version 5.0 and above
9 levels : Domain / Supergroup / Division / Subdivision / Class / Order / Family / Genus / Species

Version 4.14.1 and below
8 levels : Kingdom / Supergroup / Division / Class / Order / Family / Genus / Species
```

Just wondering how results compare to taxonomic identifications I previously did of the same sequences with other tools.

Best,
Sam

**Comment by hildebra** [comment]
Hey Sam,
we use the gb203 release. If I remember correctly, this was from
http://5.196.17.195/pr2/download/representative_sequence_of_each_cluster/gb203_pr2_all_10_28_99p.fasta.tar.gz
best,
Falk

**Comment by hildebra** [comment]
PS: in KSGP a newer PR2 DB was used, where the tax levels were adapted to fit to 7
