### ISSUE TITLE
RDP mv file

### ISSUE THREAD

**Issue by johnrandallia** [hildebra/lotus2#55]
I'm running lotus2 mostly with the default settings, but for the RDPclassifier I get an error in the following line

`systemL "mv $outdir/hierachy_cnt.tax $outdir/cnadjusted_hierachy_cnt.tax $extendedLogD/;";`

Lotus2 stops because cnadjusted_hierachy_cnt.tax does not exist.

When looking through the output folder the hierachy_cnt.tax file is located in a subfolder (ExtraFiles). 

If I paste cnadjusted_hierachy_cnt.tax in the output folder (before lotus2 executes RDP) it works.

**Comment by hildebra** [comment]
Hey John,
I changed the latest lotus2 version that should no longer try to copy files that are no longer there. Can you check if this version still crashes for you?
best, Falk

**Comment by johnrandallia** [comment]
Its working now, Thank you!
