### ISSUE TITLE
BOLD DB with COI references

### ISSUE THREAD

**Issue by johnrandallia** [hildebra/lotus2#57]
Would be amazing if you could add a COI Reference DB in future updates.
Is there a workaround for now or more detailed information on how I can use a custom DB?
E.g. a tool to create the tax4refDB file?

**Comment by hildebra** [comment]
Hey John,
this is currently not supported, but let me know if you're interested in a collab, maybe we can support on a specific project. However, I think by just setting the sdm filter parameters sensibly and providing a custom DB, you could get an already workable solution with the current lotus2.
for running a custom database in LotuS2, follow these instructions:
https://github.com/hildebra/lotus2?tab=readme-ov-file#coustom-reference-database
and
https://lotus2.earlham.ac.uk/main.php?site=documentation#usage (section refDB and tax4refDB )
hth,
Falk
