### ISSUE TITLE
error when using DADA2

### ISSUE THREAD

**Issue by we32i225** [hildebra/lotus2#58]
Hi, i have been using Lotus2 with no issue for some time now clustering via OTUs (standard 16s microbiome data). I have tried to change from UPARSE to DADA2. i have followed the suggestions on the lotus website but it doesn't seem to run. Is there a clear error in my input? (code below)

./lotus2 -i Will -o output_SLV_DADA2_2024 -m WillMAP.txt -refDB SLV -CL dada2 -taxAligner lambda

all help is appreciated 
-Will

**Comment by we32i225** [comment]
sorry falk just realised i asked this a few months back haha

**Comment by ozkurt** [comment]
Hi Will,

Could you please share your log files with me?

Thanks,
Ezgi
