### ISSUE TITLE
AmpliconShortPE usage

### ISSUE THREAD

**Issue by rigormortis0** [hildebra/lotus2#62]
Dear all, 

We have been using Lotus2 to analyse Illumina 16S data and have a question regarding the AmpliconShortPE option in the sdm config file.
Until now we used AmpliconShortPE T, as recommended by the documentation, "if your amplicons are possibly shorter than a single read in a paired end sequencing" and "if in doubt just set to T". In the sdm configuration file miSeq2.txt it is written that the AmpliconShortPE is set to T when amplicons are shorter than a single read, with the given example being  (e.g. amplicon length is 200bp in a 250x2 miSeq run, set this to "T"), while in the sdm configuration page https://lotus2.earlham.ac.uk/main.php?site=sdm_configuration, you give the example of a amplicon being longer then a single read (e.g. amplicon of 300bp in 250x2 miSeq) but setting it to true also. Would it be possible to clarify the role of AmpliconShortPE option in lotus2.

Thank you for your help,
João Colaço

**Comment by hildebra** [comment]
Hey João,
thanks for pointing this out, we'll change the webpage. 
The option is for amplicons shorter that read1/read2 length. So in case you have an amplicon of 150bp, but your read1 is 250 bp, you might find the fwd AND rev primer on read1 (as well as both on read2). In this case we would need to make sure read1 is scanned for the reverse primer, and read2 is scanned for the fwd primer, and only 1 read is used for the final clustering/abundance estimation.
Best, 
Falk
