### ISSUE TITLE
GG2 DB file not installed in update

### ISSUE THREAD

**Issue by we32i225** [hildebra/lotus2#66]
Hi, recently updated my Lotus2 (git pull method) as i saw on the website GG2 is now offered (which is great! :)). However when i updated the DB files were not installed and now running -refDB GG2 cannot locate the files (although it acknowledges that greengenes2 is an option).

Do the DB files for GG2 need to be downloaded separately or was there an error in my lotus2 update? If manual download is required, is there a Lotus2 compatible GG2 download available?

Thanks!
Will

**Comment by hildebra** [comment]
Hey Will,
it could be that there was a problem updating the old install. Could you try to do a clean git clone in a new dir?
Please let me know if this solved the problem, will make it easier to debug/update the readme.
best,
Falk

**Comment by hildebra** [comment]
ok thx Will, I'll add something to the Readme
