### ISSUE TITLE
processing

### ISSUE THREAD

**Issue by CFox-Lin** [hildebra/lotus2#68]
When I use RDPClassifier to annotate my fungi data, the program aborted with:
`ITS region was chosen as target; this requires a similarity based taxonomic annotation and excludes RDP tax annotation.
Blast similarity based annotation is not possible due to: Similarity search was not explicitly activated (please use option "-taxAligner usearch" or vsearch,lambda,blast).
`
However, RDPClassifier is able to process ITS data with `--g [fungallsu|fungalits_warcup|fungalits_unite]`, will this be possible in future version?
Thanks

**Comment by hildebra** [comment]
Hey,
we never implemented this in LotuS2, therefore the warning so the user is aware that this currently can't be done. However, this looks like an easy enough implementation, we can have a look in the next weeks.
best,
Falk
