### ISSUE TITLE
Option to handle read-through into primer for its sequences

### ISSUE THREAD

**Issue by paulzierep** [hildebra/lotus2#69]
We want to use lotus2 to analyze ITS sequences. A common issue is the read-through into the opposite primer as described in the dada2 toturial: https://benjjneb.github.io/dada2/ITS_workflow.html
Can lotus trim primers in such cases. I could not find it in the docs. Alternatively one could use cutadapt and then use lotus2 on the trimmed reads I guess...
We will develop a toturial for such as case in Galaxy and I wanted to check what would be the best approach from your point of view ?

**Comment by hildebra** [comment]
Hey Paul,
indeed, this case can happen and should be automatically processed in LotuS2. In the "ITS" sdm configs there should be the following flag set to "T":

#this option should be "T" if your amplicons are possibly shorter than a single read in a paired end sequencing run (e.g. if the 16S amplicon length is 200bp in a 250x2 miSeq run, set this to "T"). This option increases runtime by 10%, if in doubt just set to "T". *Requires* LinkerPrimerSequence and ReversePrimer to be defined in mapping file.
AmpliconShortPE	T

did this work as expected for you?

best, Falk

**Comment by paulzierep** [comment]
Ah perfect, that is probably what we need, will test if it trims as expected and let you know.
