### ISSUE TITLE
Errors with SDM

### ISSUE THREAD

**Issue by thecrobe** [hildebra/lotus2#70]
Hello, I am running Lotus2 on merged paired end illumina reads and am coming up with a weird issue. I am able to go through read filtering then I get an error tha the SDM file is not empty, but when i look it is empty. This stops the program. Do you have an idea what the issue could be? I have updated Lotus2 from conda and tried github version, and rebuilt the SDM now. 

tar: Removing leading `/' from member names
rm: cannot remove '/data/16sVU/Output/LotuSLogS//SDMperFile/': Directory not empty

Thanks! 
Justin

**Comment by hildebra** [comment]
Hey Justin,
Sorry can't really see where this might be coming from. Did you try removing the output dir by hand? Btw, the two lines you pasted above do seem to come from the perl script, not from sdm.
best,
Falk
