### ISSUE TITLE
Can't open myTestRun/tmpFiles//RDPotus.tax : 

### ISSUE THREAD

**Issue by Natalie-koks** [hildebra/lotus2#72]
I am trying to run the example command : 
lotus2 -i ~/miniconda3/pkgs/lotus2-2.32-hdfd78af_1/share/lotus2-2.32-1/Example/ -m ~/miniconda3/pkgs/lotus2-2.32-hdfd78af_1/share/lotus2-2.32-1/Example/miSeqMap.sm.txt -o myTestRun
It starts running smoothly, creates the myTestRun folder but breaks after this point, 

"00:00:14 Assigning taxonomy with RDP" 
--------------------------------------------------------------------------------
This is the error I get. It is unable to create the RDPotus file. 
Can't open myTestRun/tmpFiles//RDPotus.tax : 
No such file or directory at /home/Users/nk62/miniconda3/envs/analysis/bin/lotus2 line 4502.
Wondering if there is something I am particularly doing wrong. Any help?

**Comment by hildebra** [comment]
Hey Natalie,
this is probably related to java JRE not being installed on the system. can you check in the LotuSLogs/LotuS_progout.log file for the error that the program was producing? if it is related to java, you need to install jre in your conda environment, e.g. this might be a good start: https://anaconda.org/bioconda/java-jdk
hth, Falk

**Comment by Natalie-koks** [comment]
Thank you very much
