### ISSUE TITLE
Possibility to get similar ASVs for multiple runs

### ISSUE THREAD

**Issue by paulzierep** [hildebra/lotus2#73]
We would like to use lotus2 to generate inputs for ML models. We are facing the issue, that for each run a different assignment of ASVs is done. So ASV1 does not correspond to the same sequence for each run. For the models, it would be ideal if the column of the OTU/ASV would be comparable between runs. We can also merge tables based on taxonomy instead of ASV assignment. But ASV would be preferred. Do you have any idea how that could be achieved ? 

My idea would be to use the `FASTA-formatted extended OTU seed sequences` to create a mapping table between asv's from different runs, but maybe you have a simpler approach ?

**Comment by hildebra** [comment]
Hey,
yes the ASV num will be randomized. You can use the dada2 approach, which is to use the ASV sequence as "name" of the ASV, i..e do a direct string match for each ASV between datasets.. but I would not want to guarantee that you always get exactly the same ASV nt sequence (although dada2 seems to think this is a viable strategy).

If I had to this, I would run all the different datasets together, at least you'll get the same ASV's. But you will have information flow between the different datasets. 
Alternatively you could try direct nt seq string matches, but then I think it would be prudent to check with 99% sequence similarity for the non-matching ASVs.
Last, you could go with species level assignments, but this can lead to problems if you ASV only gets assigned to family or class lelve.

hth,
Falk

**Comment by paulzierep** [comment]
Thank you @hildebra for the informative feedback. Multiple Options to follow up here. Eventually what I will do is to concatenate the rank assignment for each rank and merge the table based on this, which should include all features and allows merging of table even with newly generated tables (inner join, to avoid issues if new assignments are done)
