### ISSUE TITLE
V-Xtractor HMM database

### ISSUE THREAD

**Issue by nsoranzo** [hildebra/lotus2#8]
Question: Is lOTUs using the HMM database shipped in http://software.microbiome.ch/vxtractor.zip (linked from https://www.microbiome.ch/software ) ? It seems the main ones in http://lotus2.earlham.ac.uk/lotus/packs/VXtractor/HMMs.zip are neither the LSU or SSU ones.

I am considering what would be best for the lOTUs conda package, do we need a conda package for V-Xtractor ? Just the Perl script or also the HMM database(s)?

**Comment by hildebra** [comment]
Hey, I'm currently testing the V-Xtractor, but not sure it will make it in the final version.  This is the correct one:  http://software.microbiome.ch/vxtractor.zip.
On http://lotus2.earlham.ac.uk/lotus/packs/VXtractor/HMMs.zip , the SSU and LSU folders are in the main dir for me, these should work.

**Comment by nsoranzo** [comment]
In http://lotus2.earlham.ac.uk/lotus/packs/VXtractor/HMMs.zip , the `archea`, `bacteria` and `fungi` directories appear in 3 places: main directory, inside LSU and inside SSU. The original archive from microbiome.ch doesn't have them in the main directory, which generated my question, but you are right that the ones in the main directory seem not to be used by lOTUs.
