### ISSUE TITLE
Need non-interactive installation method

### ISSUE THREAD

**Issue by nsoranzo** [hildebra/lotus2#9]
Presently the `autoInstall.pl` script requires user input from the console.
To create a conda package for lOTUs we can skip calling `autoInstall.pl` for the software dependencies (since these will be installed via package requirements), but the required databases need to be installed/uninstalled as part of the lotus package installation/uninstallation, i.e. via `post-link.sh`/`pre-unlink.sh` scripts distributed with the conda package. In these scripts we could just run `autoInstall.pl` with some combination of parameters, but the script must be updated to be callable non-interactively.

**Comment by hildebra** [comment]
I added a flag now to autinstall. Calling "perl autoInstall.pl -condaDBinstall" should do the trick, can you try?

For now, I left the R autoInstall.R active (will try to automatically load required R libs, if not present, will install them), or should this become inactive as well?
Usearch install is still a problem. I think this needs to be done manually, but I could ask Robert Edgar. For now, I programmed the installer to just go through everything, but the user needs to still link usearch later to their conda-lotus2 install by themselves.

**Comment by nsoranzo** [comment]
> I added a flag now to autinstall. Calling "perl autoInstall.pl -condaDBinstall" should do the trick, can you try?

Thanks a lot!

> For now, I left the R autoInstall.R active (will try to automatically load required R libs, if not present, will install them), or should this become inactive as well?

Yes, can you please disable installation of R packages as well when using `-condaDBinstall` ?

> Usearch install is still a problem. I think this needs to be done manually, but I could ask Robert Edgar. For now, I programmed the installer to just go through everything, but the user needs to still link usearch later to their conda-lotus2 install by themselves.

My plan is to have the lotus2 conda package depend on [vsearch](https://github.com/torognes/vsearch) and then users can install usearch manually and replace the path in `lOTUs.cfg` .

**Comment by nsoranzo** [comment]
Ah, can you also disable installation of ITSx, please?

**Comment by hildebra** [comment]
Hey, please see updated git, should now have this implemented.
About usearch: ok, I will over time also integrate more help on this within LotuS2 then.

**Comment by nsoranzo** [comment]
Thanks, I think we are almost there! In the `bin` directory there are still 3 executables that should probably not be shipped with lOTUs source: `LCA`, `rtk` and `sdm`. Do you think they can be removed from the git repository?

**Comment by hildebra** [comment]
Hey Nicola, no these are there on purpose, since these are static compiles and shipping the C++ source code has caused too many difficulties to users in the past (these are C++ programs that are part of lotus). Is it possible to ship these with conda? O/w I can give you access to the latest source code, but these are moving targets that will update with LotuS versions..

**Comment by nsoranzo** [comment]
Yes, they are all available in conda thanks to @telatin ! Ideally, the best practice when you need to update one of these would be:
- create a new release (e.g. https://github.com/hildebra/LCA/releases/new ), attaching also a static-compiled binary
- in lOTUs' `autoInstall.pl` , download and install the static-compiled binary from GitHub, except when `-condaDBinstall` is specified.

**Comment by hildebra** [comment]
If these are old version from some time ago, they don't work at all with current LotuS, so careful with these.

**Comment by nsoranzo** [comment]
The latest versions on Bioconda are:
- LCA 0.18
- rtk 0.93.2
- sdm 1.47

which are all more than 1 year old. Having official releases on GitHub for these would be greatly helpful to keep them updated.
